### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by lbdyck** [leppanayr/RexxEditor2#1]
I installed Eclipse today and noticed there wasn't a REXX plugin, so off to github to search and found yours.  I cloned it to my windows PC but could not find any information on how to install and use it.

Any help would be appreciated.

Thank you

**Comment by RappelBerryPi** [comment]
Hello, 
You’ll have to give me some time to make it home and give some instructions. For now to test it out you can run the code by opening the project and running as an eclipse application to test out its functionality. 
It’s got a long way to go but I eventually plan to get it to the eclipse marketplace and you’ll be able to install it from there without issue.

**Comment by RappelBerryPi** [comment]
I added a release with an update site set up as a zip file. follow the instructions in the release information and you'll be able to install it into eclipse. There is a Context Assistance feature that I'm currently working on to show function definitions inside of Michael Colishaw's "The REXX Language" book as well as some off of IBM's website. This will be included in the next release, and then I'll start working on a content outliner and other features. If you have any suggestions I'm open to them!

**Comment by lbdyck** [comment]
Thank you very much - i'll play with it later today.

**Comment by lbdyck** [comment]
I may be missing something but i tried without success.
1. downloaded the zip
2. tried to install from eclipse pointing to the .zip - no joy
3. unzip'd - tried the install pointing to the unzip directory - no joy
4. tried pointing to several of the directories without success

thanks for any help.

**Comment by RappelBerryPi** [comment]
I added a video on how to install the zip in eclipse. Hopefully that should help you. I'll reopen this until you can successfully get it installed. The video is in the release for [0.1.0](https://github.com/leppanayr/RexxEditor/releases/tag/0.1.0)

**Comment by lbdyck** [comment]
Perfect - got it installed - didn't know about the archive option (still learning eclipse)

Great job....!
